### ISSUE TITLE
My issues

### ISSUE THREAD

**Issue by rylasasin** [daunknownfox2010/half-life-2-campaign#5]
I have two:

First, it seems to keep spamming my console with 

`[Half-Life 2 Campaign] gamemodes/half-life_2_campaign/gamemode/sh_init.lua:172: Calling net.Start with unpooled message name! [ http://goo.gl/qcx0y ]
  1. Start - [C]:-1
   2. unknown - gamemodes/half-life_2_campaign/gamemode/sh_init.lua:172
`

And secondly, Item pickups (health, ammo, etc) do not work.

**Comment by daunknownfox2010** [comment]
Please make sure you do not have any conflicting addons installed and running, then try again. This is not a gamemode issue.
